events { worker_connections 1024; }

http {
    # 1. STREAMLIT
    server {
        listen 80;
        server_name dashboard.finance localhost;

        location / {
            proxy_pass http://streamlit_tfm:8501;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # 2. GRAFANA
    server {
        listen 80;
        server_name grafana.finance;

        location / {
            proxy_pass http://grafana_tfm:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # 3. PGADMIN
    server {
        listen 80;
        server_name bbdd-pg.finance;

        location / {
            proxy_pass http://pgadmin_tfm:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}