{
 "title": "Termómetro financiero",
 "time": { "from": "2000-10-31T12:04:37.000Z", "to": "2025-12-20T11:36:09.000Z" },
 "templating": {
  "list": [
   {
    "name": "var_user_id",
    "query": "SELECT DISTINCT user_id FROM usuarios;"
   }
  ]
 },
 "panels": [
  {
   "title": "Saldo total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "economia_db",
     "rawSql": "SELECT \r\n  SUM(saldo_actual) AS value,\r\n  'Total Cuentas' AS metric\r\nFROM cuentas\r\nWHERE user_id = ${var_user_id};"
    }
   ]
  },
  {
   "title": "Últimas transacciones",
   "type": "table",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "economia_db",
     "rawSql": "SELECT \r\n  fecha, \r\n  concepto, \r\n  monto, \r\n  categoria \r\nFROM transacciones \r\nWHERE user_id = ${var_user_id} \r\nORDER BY fecha DESC \r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Gastos por categoría",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "dataset": "economia_db",
     "rawSql": "SELECT \r\n  categoria, \r\n  SUM(monto) AS total \r\nFROM transacciones \r\nWHERE user_id = ${var_user_id} \r\n  AND tipo = 'gasto' \r\nGROUP BY categoria;"
    }
   ]
  }
 ]
}